#!/usr/bin/env python3
from __future__ import annotations
import subprocess
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
MEM = ROOT / "memory-bank"
IGNORE_DIRS = {".git","node_modules","dist","build","coverage",".cache","tmp","temp","logs","vendor","venv",".venv","__pycache__","target","bin","obj",".next",".nuxt",".idea",".vscode"}
TEXT_EXTS = {".py",".ts",".tsx",".js",".jsx",".mjs",".cjs",".java",".go",".rs",".rb",".php",".cs",".cpp",".cc",".c",".h",".hpp",".swift",".kt",".scala",".lua",".sql",".sh",".ps1",".yaml",".yml",".json",".toml",".ini",".cfg",".env",".md",".txt",".xml",".html",".css"}

def rel(p: Path) -> str:
    return "/" + str(p.relative_to(ROOT)).replace("\\", "/")

def wanted(p: Path) -> bool:
    if any(part in IGNORE_DIRS for part in p.parts):
        return False
    return p.suffix.lower() in TEXT_EXTS or p.name in {"Dockerfile","Makefile","AGENTS.md","README.md"}

def read_head(p: Path, n=60):
    try:
        with p.open("r", encoding="utf-8", errors="ignore") as f:
            return [line.rstrip() for _, line in zip(range(n), f)]
    except Exception:
        return []

def role(p: Path, lines):
    name = p.stem.lower()
    if name in {"main","index","app","server"}: return "likely entrypoint"
    if "route" in name or "router" in name: return "routing layer"
    if "service" in name: return "service logic"
    if "model" in name or "schema" in name: return "data model/schema"
    if "config" in name or "settings" in name: return "configuration"
    return "source file"

def symbols(lines):
    out = []
    for s in [line.strip() for line in lines]:
        for prefix in ("export function ","export const ","export class ","export default ","def ","class ","func ","pub fn "):
            if s.startswith(prefix):
                name = s[len(prefix):].split("(")[0].split("{")[0].split(":")[0].strip()
                if name: out.append(name)
        if len(out) >= 6: break
    return out

files = [p for p in ROOT.rglob("*") if p.is_file() and wanted(p) and ".generated.md" not in p.name][:800]
files = sorted(files)

repo_lines = ["# repoMap.generated.md","","_Generated by scripts/generate_repo_index.py_",""]
groups = {}
for p in files:
    top = p.relative_to(ROOT).parts[0]
    groups.setdefault(top, []).append(p)
for top in sorted(groups):
    repo_lines.append(f"## /{top}")
    for p in groups[top][:50]:
        repo_lines.append(f"- {rel(p)} — {role(p, read_head(p, 20))}")
    if len(groups[top]) > 50:
        repo_lines.append(f"- ... ({len(groups[top]) - 50} more files)")
    repo_lines.append("")
(MEM / "repoMap.generated.md").write_text("\n".join(repo_lines).strip() + "\n", encoding="utf-8")

inv = ["# fileInventory.generated.md","","_Generated by scripts/generate_repo_index.py_",""]
for p in files:
    head = read_head(p, 60)
    inv.append(f"## {rel(p)}")
    inv.append(f"- role: {role(p, head)}")
    inv.append(f"- last_modified: {datetime.fromtimestamp(p.stat().st_mtime).strftime('%Y-%m-%d %H:%M')}")
    syms = symbols(head)
    if syms:
        inv.append(f"- symbols: {', '.join(syms)}")
    inv.append("")
(MEM / "fileInventory.generated.md").write_text("\n".join(inv).strip() + "\n", encoding="utf-8")

recent = ["# recentChanges.generated.md","","_Generated by scripts/generate_repo_index.py_","","## Git-based change signals"]
try:
    status = subprocess.run(["git","status","--short"], cwd=ROOT, capture_output=True, text=True, check=False)
    recent.append(status.stdout.strip() or "No git change information available.")
except Exception:
    recent.append("No git change information available.")
recent += ["","## Most recently modified files"]
for p in sorted(files, key=lambda x: x.stat().st_mtime, reverse=True)[:25]:
    recent.append(f"- {rel(p)} — {datetime.fromtimestamp(p.stat().st_mtime).strftime('%Y-%m-%d %H:%M')}")
(MEM / "recentChanges.generated.md").write_text("\n".join(recent).strip() + "\n", encoding="utf-8")

print("Generated repo index files in memory-bank/")
